In [1]:
import pandas as pd
import numpy as np
import requests

In [2]:
products_url = "https://dummyjson.com/products"
users_url = "https://dummyjson.com/users"
carts_url = "https://dummyjson.com/carts"

In [3]:
#products
res1 = requests.get(products_url)
print("Products Status: ", res1.status_code)

if res1.status_code == 200:
    products_data = res1.json()['products']
    df_products = pd.DataFrame(products_data)

Products Status:  200

In [4]:
#user
res2 = requests.get(users_url)
print("Users Status: ", res2.status_code)

if res2.status_code == 200:
    users_data = res2.json()['users']
    df_users = pd.DataFrame(users_data)

Users Status:  200

In [5]:
#carts
res3 = requests.get(carts_url)
print("Carts Status: ", res3.status_code)

if res3.status_code == 200:
    carts_data = res3.json()['carts']
    df_carts = pd.DataFrame(carts_data)

Carts Status:  200

In [6]:
df_products.head()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,"{'width': 15.14, 'height': 13.08, 'depth': 22.99}",1 week warranty,Ships in 3-5 business days,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,"{'width': 9.26, 'height': 22.47, 'depth': 27.67}",1 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,"{'width': 29.27, 'height': 27.93, 'depth': 20.59}",3 months warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,"{'width': 18.11, 'height': 28.38, 'depth': 22.17}",3 year warranty,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,40,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,"{'width': 21.63, 'height': 16.48, 'depth': 29.84}",1 month warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Poor quality!', 'da...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...

In [7]:
df_users.head()

,id,firstName,lastName,maidenName,age,gender,email,phone,username,password,...,address,macAddress,university,bank,company,ein,ssn,userAgent,crypto,role
0,1,Emily,Johnson,Smith,29,female,emily.johnson@x.dummyjson.com,+81 965-431-3024,emilys,emilyspass,...,"{'address': '626 Main Street', 'city': 'Phoeni...",47:fa:41:18:ec:eb,University of Wisconsin--Madison,"{'cardExpire': '05/28', 'cardNumber': '3693233...","{'department': 'Engineering', 'name': 'Dooley,...",977-175,900-590-289,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
1,2,Michael,Williams,,36,male,michael.williams@x.dummyjson.com,+49 258-627-6644,michaelw,michaelwpass,...,"{'address': '385 Fifth Street', 'city': 'Houst...",79:15:78:99:60:aa,Ohio State University,"{'cardExpire': '01/30', 'cardNumber': '3530633...","{'department': 'Support', 'name': 'Spinka - Di...",912-602,108-953-962,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
2,3,Sophia,Brown,,43,female,sophia.brown@x.dummyjson.com,+81 210-652-2785,sophiab,sophiabpass,...,"{'address': '1642 Ninth Street', 'city': 'Wash...",12:a3:d3:6f:5c:5b,Pepperdine University,"{'cardExpire': '10/27', 'cardNumber': '6011212...","{'department': 'Research and Development', 'na...",963-113,638-461-822,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
3,4,James,Davis,,46,male,james.davis@x.dummyjson.com,+49 614-958-9364,jamesd,jamesdpass,...,"{'address': '238 Jefferson Street', 'city': 'S...",10:7d:df:1f:97:58,University of Southern California,"{'cardExpire': '07/30', 'cardNumber': '5303440...","{'department': 'Support', 'name': 'Pagac and S...",904-810,116-951-314,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
4,5,Emma,Miller,Johnson,31,female,emma.miller@x.dummyjson.com,+91 759-776-1614,emmaj,emmajpass,...,"{'address': '607 Fourth Street', 'city': 'Jack...",32:b9:7e:8d:f5:e8,Northeastern University,"{'cardExpire': '07/30', 'cardNumber': '5237188...","{'department': 'Human Resources', 'name': 'Gra...",403-505,526-210-885,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:9...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin

In [8]:
df_carts.head()

,id,products,total,discountedTotal,userId,totalProducts,totalQuantity
0,1,"[{'id': 162, 'title': 'Blue Frock', 'price': 2...",13037.88,11510.81,1,4,12
1,2,"[{'id': 86, 'title': 'Man Short Sleeve Shirt',...",139.93,125.70,2,2,7
2,3,"[{'id': 24, 'title': 'Fish Steak', 'price': 14...",1794.85,1625.77,3,6,15
3,4,"[{'id': 92, 'title': 'Sports Sneakers Off Whit...",689.93,636.81,4,2,7
4,5,"[{'id': 161, 'title': 'Samsung Galaxy Tab Whit...",1467.88,1205.80,5,3,12

In [9]:
df_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    30 non-null     int64
 1   title                 30 non-null     object
 2   description           30 non-null     object
 3   category              30 non-null     object
 4   price                 30 non-null     float64
 5   discountPercentage    30 non-null     float64
 6   rating                30 non-null     float64
 7   stock                 30 non-null     int64
 8   tags                  30 non-null     object
 9   brand                 15 non-null     object
 10  sku                   30 non-null     object
 11  weight                30 non-null     int64
 12  dimensions            30 non-null     object
 13  warrantyInformation   30 non-null     object
 14  shippingInformation   30 non-null     object
 15  availabilityStatus    30 non-null     object
 16  reviews               30 non-null     object
 17  returnPolicy          30 non-null     object
 18  minimumOrderQuantity  30 non-null     int64
 19  meta                  30 non-null     object
 20  images                30 non-null     object
 21  thumbnail             30 non-null     object
dtypes: float64(3), int64(4), object(15)
memory usage: 5.3+ KB

In [10]:
df_users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 28 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          30 non-null     int64
 1   firstName   30 non-null     object
 2   lastName    30 non-null     object
 3   maidenName  30 non-null     object
 4   age         30 non-null     int64
 5   gender      30 non-null     object
 6   email       30 non-null     object
 7   phone       30 non-null     object
 8   username    30 non-null     object
 9   password    30 non-null     object
 10  birthDate   30 non-null     object
 11  image       30 non-null     object
 12  bloodGroup  30 non-null     object
 13  height      30 non-null     float64
 14  weight      30 non-null     float64
 15  eyeColor    30 non-null     object
 16  hair        30 non-null     object
 17  ip          30 non-null     object
 18  address     30 non-null     object
 19  macAddress  30 non-null     object
 20  university  30 non-null     object
 21  bank        30 non-null     object
 22  company     30 non-null     object
 23  ein         30 non-null     object
 24  ssn         30 non-null     object
 25  userAgent   30 non-null     object
 26  crypto      30 non-null     object
 27  role        30 non-null     object
dtypes: float64(2), int64(2), object(24)
memory usage: 6.7+ KB

In [11]:
df_carts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               30 non-null     int64
 1   products         30 non-null     object
 2   total            30 non-null     float64
 3   discountedTotal  30 non-null     float64
 4   userId           30 non-null     int64
 5   totalProducts    30 non-null     int64
 6   totalQuantity    30 non-null     int64
dtypes: float64(2), int64(4), object(1)
memory usage: 1.8+ KB

In [12]:
df_products = df_products[['id', 'title', 'price', 'category', 'rating']]

In [13]:
df_products.rename(columns = {'id':'product_id'}, inplace = True)

In [14]:
df_products.head()

   product_id                          title  price category  rating
0           1  Essence Mascara Lash Princess   9.99   beauty    2.56
1           2  Eyeshadow Palette with Mirror  19.99   beauty    2.86
2           3                Powder Canister  14.99   beauty    4.64
3           4                   Red Lipstick  12.99   beauty    4.36
4           5                Red Nail Polish   8.99   beauty    4.32

In [15]:
# full name
df_users['full_name'] = df_users['firstName'] + " " + df_users['lastName']

In [16]:
#extract city from nested Address
df_users['city'] = df_users['address'].apply(lambda x: x['city'])

In [17]:
df_users = df_users[['id', 'full_name', 'city', 'gender', 'age']]

In [18]:
df_users.rename(columns = {'id':'user_id'}, inplace=True)

In [19]:
df_users.head()

   user_id         full_name          city  gender  age
0        1     Emily Johnson       Phoenix  female   29
1        2  Michael Williams       Houston    male   36
2        3      Sophia Brown    Washington  female   43
3        4       James Davis       Seattle    male   46
4        5       Emma Miller  Jacksonville  female   31

In [20]:
#transforming  Carts
#convert nested list to rows
df_carts= df_carts.explode('products')

In [21]:
df_carts.head()

,id,products,total,discountedTotal,userId,totalProducts,totalQuantity
0,1,"{'id': 162, 'title': 'Blue Frock', 'price': 29...",13037.88,11510.81,1,4,12
0,1,"{'id': 113, 'title': 'Generic Motorcycle', 'pr...",13037.88,11510.81,1,4,12
0,1,"{'id': 122, 'title': 'iPhone 6', 'price': 299....",13037.88,11510.81,1,4,12
0,1,"{'id': 138, 'title': 'Baseball Ball', 'price':...",13037.88,11510.81,1,4,12
1,2,"{'id': 86, 'title': 'Man Short Sleeve Shirt', ...",139.93,125.70,2,2,7

In [22]:
#extract product id and quantity
df_carts['product_id'] = df_carts['products'].apply(lambda x: x['id'])
df_carts['quantity'] = df_carts['products'].apply(lambda x: x['quantity'])

In [23]:
df_carts.drop(columns = ['products'], inplace = True)

In [24]:
#rename columns
df_carts.rename(columns = {'id':'cart_id', 'userId':'user_id'}, inplace=True)

In [25]:
df_carts.head()

,cart_id,total,discountedTotal,user_id,totalProducts,totalQuantity,product_id,quantity
0,1,13037.88,11510.81,1,4,12,162,4
0,1,13037.88,11510.81,1,4,12,113,3
0,1,13037.88,11510.81,1,4,12,122,3
0,1,13037.88,11510.81,1,4,12,138,2
1,2,139.93,125.70,2,2,7,86,5

### Feature Engineering

In [26]:
#merge with product table to get price
df_carts = df_carts.merge(df_products, on='product_id', how='left')

In [27]:
#revenue calculation
df_carts['revenue'] = df_carts['price'] * df_carts['quantity']

In [28]:
df_carts.head()

,cart_id,total,discountedTotal,user_id,totalProducts,totalQuantity,product_id,quantity,title,price,category,rating,revenue
0,1,13037.88,11510.81,1,4,12,162,4,NaN,NaN,NaN,NaN,NaN
1,1,13037.88,11510.81,1,4,12,113,3,NaN,NaN,NaN,NaN,NaN
2,1,13037.88,11510.81,1,4,12,122,3,NaN,NaN,NaN,NaN,NaN
3,1,13037.88,11510.81,1,4,12,138,2,NaN,NaN,NaN,NaN,NaN
4,2,139.93,125.70,2,2,7,86,5,NaN,NaN,NaN,NaN,NaN

In [29]:
df_carts.duplicated().sum()

np.int64(1)

In [30]:
df_carts.drop_duplicates(inplace = True)
df_users.drop_duplicates(inplace = True)
df_products.drop_duplicates(inplace = True)

In [31]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in C:\Users\Dheeraj\anaconda3\Lib\site-packages (2.0.39)
Requirement already satisfied: pymysql in C:\Users\Dheeraj\anaconda3\Lib\site-packages (1.1.2)
Requirement already satisfied: greenlet!=0.4.17 in C:\Users\Dheeraj\anaconda3\Lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Dheeraj\anaconda3\Lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [32]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus("WRITE YOUR PASSWORD")

engine = create_engine(f"mysql+pymysql://root:{password}@localhost:3306/ecommerce")

engine.connect()

print("✅ Connected successfully!")

✅ Connected successfully!

In [33]:
df_products.to_sql("products", engine, if_exists="replace", index=False)
df_users.to_sql("users", engine, if_exists="replace", index=False)
df_carts.to_sql("orders", engine, if_exists="replace", index=False)

113

In [34]:
df_products.to_csv("products.csv",index=False)

In [35]:
df_users.to_csv("users.csv",index=False)

In [36]:
df_carts.to_csv("carts.csv",index=False)